### ISSUE TITLE
reintroduce `coalton-codegen-types` or equivalent

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#1017]
It got lost. I would either want the operator back, or perhaps just a global variable option.

**Comment by macrologist** [comment]
With what inputs are you looking for what outputs?

**Comment by stylewarning** [comment]
coalton-codegen-types is identical to coalton-codegen except the special variable that controls whether Lisp type declarations are emitted is set to T. 

The lisp type decls are usually way too noisy, hence off by default.
