### ISSUE TITLE
isqrt overflows

### ISSUE THREAD

**Issue by herbertjones** [coalton-lang/coalton#1032]
I'm not sure if this a failure for specialization to fire or this is intended, but the Integral instance of `isqrt` is used instead where I would expect the specialized version to.

```text
> (coalton (the u32 (math:isqrt 65536)))
256 (9 bits, #x100)
```

However

```lisp
  (declare test-isqrt ((Integral :a) => :a -> :a))
  (define (test-isqrt n)
    (math:isqrt n))
```

```text
> (coalton (test-isqrt (the u64 65536)))
256 (9 bits, #x100)
```

is good.  But,

```text
> (coalton (test-isqrt (the u32 65536)))
; Debugger entered on #<COMMON-LISP:DIVISION-BY-ZERO {10099B1B93}>
```

errors, which is due to

```lisp
  (declare isqrt ((Integral :int) => :int -> :int))
  (define (isqrt x)
    "The floor of the square root of N > 0."
    (let ((isqrt-rec 
            (fn (a)
              (let b = (quot (+ (* a a) x)  ;; <- 4294967296 exceeds max bounds of u32
                             (* 2 a)))
              (if (> a b)
                  (isqrt-rec b)
                  a))))
      (cond
        ((> x 1) (isqrt-rec x))
        ((== x 1) 1)
        ((== x 0) 0)
        ((< x 0) (error "Cannot take ISQRT of a negative number."))))))
```

I'm not sure if the problem is the non specialized `isqrt` isn't written in such a way to handle overflows and that is expected to be called, or that the specialization functionality is not working.

**Comment by eliaslfox** [comment]
The default version of `isqrt` should work. The specialization will not be called in all circumstances.

I'll have to think about this a bit.
