### ISSUE TITLE
Another installation issue with Eclector

### ISSUE THREAD

**Issue by mclements** [coalton-lang/coalton#1051]
Installing using GitHub under `local-projects` for Quicklisp using `(ql:quickload "coalton")`, I got the following error:

```
[package coalton-impl/parser/reader]
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "*CLIENT*" not found in the ECLECTOR.BASE package.
;   
;       Line: 47, Column: 80, File-Position: 1585
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/marcle/quicklisp/local-projects/coalton/src/parser/reader.lisp" {1003F05003}>

```

I could fix this using:

```
modified   src/parser/reader.lisp
@@ -44,7 +44,7 @@
     nil 'eof
     nil))
 
-(defun maybe-read-form (stream &optional (eclector-client eclector.base:*client*))
+(defun maybe-read-form (stream &optional (eclector-client eclector.reader:*client*))
   "Read the next form or return if there is no next form.
 
 Returns (VALUES FORM PRESENTP EOFP)"
```

...but does anyone else have this issue and is this the right fix?

**Comment by macrologist** [comment]
I don't have that issue but I do notice that the [package.lisp](https://github.com/s-expressionists/Eclector/blob/d499b09142c7e39b4ef52e821fa767d5a8d606a0/code/base/package.lisp#L41) of `eclector.base` mentions that `*client*` is for "internal use". So even if this isn't the root problem might be nice to make the above change anyway.

**Comment by mclements** [comment]
@macrologist: how do you suggest we proceed?

**Comment by macrologist** [comment]
Could you provide feedback on the following:

1. The values of: `(lisp-implementation-version)` , `(lisp-implementation-type)`, and `(software-type)` ?
1. The value of `quicklisp:*local-project-directories*`
3. The value of `asdf:*central-registry*`
4. Are you using an alternate quicklisp dist (e.g. ultralisp)? 
5. Did you try clearing any lisp cache?  e.g. the contents of any directory matching `$HOME/.cache/common-lisp/sbcl-*/` on a linux/mac system. ?

It would be nice to diagnose the issue. The symbol that is not present on your system seems to be present on mine, defined `eclector/code/base/variables.lisp`.  So I wonder if you had an old version installed or cached.

**Comment by mclements** [comment]
Apologies for the noise: I had an old version of eclector (`eclector-20210228-git`) installed through quicklisp which did not include a `variables.lisp` file. I reinstalled quicklisp and now all is fine. In hindsight, it would have been simpler to update the quicklisp distributions.

**Comment by macrologist** [comment]
glad it was sorted out!
