### ISSUE TITLE
Using Type name instead of constructor returns opaque `unknown variable` error

### ISSUE THREAD

**Issue by Izaakwltn** [coalton-lang/coalton#1095]
This is a pretty minor nit, but when you call the type name instead of the constructor:

```
(defpackage #:unknown-variable-type-error
  (:use #:coalton
        #:coalton-prelude))

(in-package #:unknown-variable-type-error)

(coalton-toplevel

  (define-type DataType
    (Data1 Integer)
    (Data2 String))

  (define (return-data int)
    (DataType int)))
```
It returns the error: 
```
(DATATYPE INT)))
 ^^^^^^^^ unknown variable
```
Which seems vague, and also, technically it's not an _unknown_ variable.

**Comment by stylewarning** [comment]
It is an unknown variable, but we should do a check to see if the "variable" defines a type, and say "did you mean a constructor of type FOO?"
