### ISSUE TITLE
Monomorphizer tests are excluded from the test suite, is this intentional?

### ISSUE THREAD

**Issue by Izaakwltn** [coalton-lang/coalton#1126]
Currently, they are not loaded as part of `:coalton/tests`. 

I checked and they compile, run, and pass. 

https://github.com/coalton-lang/coalton/blob/05111b8a59e3f7346b175ce1ec621bff588e1e1f/tests/monomorphizer-tests.lisp

**Comment by stylewarning** [comment]
Maybe an accident. Let's ship them if they work.

**Comment by stylewarning** [comment]
(But let's also verify the tests make sense.)

**Comment by Izaakwltn** [comment]
Sounds good, I'll take a look

**Comment by Izaakwltn** [comment]
Closed by #1128
