### ISSUE TITLE
Class inheritance issue in `define-instance`

### ISSUE THREAD

**Issue by Izaakwltn** [coalton-lang/coalton#1141]
This may be user error (or ignorance), but it seems like this _should_ work.
 
Here is a boiled down example:
```
(coalton-toplevel

  (define-class (AlwaysFalse :a)
    (gimme-false (:a -> Boolean)))

  (define-instance ((Into :a UFix) => AlwaysFalse :a)
    (define (gimme-false a)
      False))

  (define-instance (AlwaysFalse (Tuple UFix IFix))
    (define (gimme-false (Tuple a b))
      False)))
```
Returns the compilation error:
```
error: Overlapping instance
  --> COALTON-TOPLEVEL (/private/var/tmp/slimeUAlBPz):4:19
   |
 4 |    (DEFINE-INSTANCE ((INTO :A UFIX) => ALWAYSFALSE :A)
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ instance overlaps with ALWAYSFALSE UFIX
```
To my eye, the instance `AlwaysFalse :a` hasn't been defined, only `(Into :a UFix => AlwaysFalse :a)`. This error would make sense if the class inheritance was declared in the class definition, but behavior should ideally be able to be generalized along independently inherited lines?

**Comment by eliaslfox** [comment]
This is the intended behavior. Instance overlap checks don't consider instance constraints. The current overlap check is very easy to implement: if two instances unify but are not equal then they overlap. See [the implementation here](https://github.com/coalton-lang/coalton/blob/main/src/typechecker/environment.lisp#L1111-L1141). Extending this to take instance constraints into account would require a much more complicated back tracking search.

GHC [also rejects this](https://play.haskell.org/saved/qNkwYhcm). Interestingly it does so at usage time not definition time. See also [this thread](https://github.com/purescript/purescript/issues/3596) about overlapping instance checks in PureScript.

**Comment by Izaakwltn** [comment]
Thanks for the indepth explanation!
