### ISSUE TITLE
FSET has compilation errors while loading Coalton via Quicklisp

### ISSUE THREAD

**Issue by lmarzocchetti** [coalton-lang/coalton#1163]
I've followed the guide to install and load Coalton, but sbcl gave me a ONCE-ONLY error while loading fset

<img width="1728" alt="Screenshot 2024-07-14 at 13 01 04" src="https://github.com/user-attachments/assets/60a1afad-e875-4709-8a99-3e440ead2867">

**Comment by stylewarning** [comment]
This is an issue with Quicklisp not having been updated.

You will need to get a copy of

- FSET: https://github.com/slburson/fset/
- MISC-EXTENSIONS https://github.com/slburson/misc-extensions/

and tell Quicklisp where they are (e.g., your ~/quicklisp/local-projects/ directory).

More details about the FSET issue is here: https://github.com/slburson/fset/issues/51

**Comment by lmarzocchetti** [comment]
So i install locally these 2 packages, instaed of installing via quicklisp, and then load coalton if i'm right?

**Comment by stylewarning** [comment]
> So i install locally these 2 packages, instaed of installing via quicklisp, and then load coalton if i'm right?

Yes. You may need to reset your ASDF cache.

**Comment by slburson** [comment]
Quicklisp has now been updated; it is no longer necessary to keep local versions of FSet and Misc-Extensions.  Just do `(ql:update-dist "quicklisp")` to get the current ones.

The section of the README that says to keep local versions can now be deleted.

**Comment by lmarzocchetti** [comment]
Thank you for your work! Love this project!
