### ISSUE TITLE
Remove `traverse` `action`s' explicit function reference passing

### ISSUE THREAD

**Issue by amorphedstar** [coalton-lang/coalton#1192]
Currently, a recursive function object `traverse` must be provided as an argument for `action`s whenever `when` is `:traverse`. https://github.com/coalton-lang/coalton/blob/main/src/codegen/traverse.lisp#L57-L61
The recursive object reference never changes over a traversal, so it could be nice to fix the reference to something not explicitly passed, using something like `dynamic extent`.

**Comment by stylewarning** [comment]
I would say we want to use a special variable (e.g., a `(defvar *foo*)`)   which is bound for the dynamic extent of the call
