### ISSUE TITLE
Error in (ql:quickload :coalton) with Portacle on Windows

### ISSUE THREAD

**Issue by thinkelman-ESA** [coalton-lang/coalton#132]
When loading `coalton` using Portacle on Windows 10, I get the error below. When loading `coalton` on Manjaro (not using Portacle), it loads correctly. Is this more likely a Windows problem or a Portacle problem?

```
CL-USER> (ql:quickload :coalton)
To load "coalton":
  Load 1 ASDF system:
    coalton
; Loading "coalton"
.....
; 
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE:
;   
;     Symbol "SINGLE-FLOAT-NAN" not found in the FLOAT-FEATURES package.
;   
;       Line: 148, Column: -1, File-Position: 4355
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file c:\\Users\\thinkelman\\portacle\\projects\\coalton\\src\\library\\arith.lisp" {1005DA5483}>
```

**Comment by colescott** [comment]
I'm thinking this might be an issue with Portacle shipping with an older quicklisp distribution which has the version of `float-features` before they introduced the NAN constants.
When you run `(ql:system-apropos "float-features")` what version of `float-features` does it show?

**Comment by thinkelman-ESA** [comment]
```
CL-USER> (ql:system-apropos "float-features")
#<SYSTEM float-features / float-features-20191007-git / quicklisp 2019-12-27>
```

**Comment by colescott** [comment]
That is a pretty old version and it wouldn't have NAN support.

You can update your quicklisp dist using `(ql:update-dist "quicklisp")` and that should give you the updated version and allow you to load coalton.

**Comment by thinkelman-ESA** [comment]
Thanks! I'm brand new to Lisp so still learning basics. Updating quicklisp gets me a new error:

```
arithmetic error FLOATING-POINT-INVALID-OPERATION signalled
Operation was (> #<DOUBLE-FLOAT quiet NaN> #<DOUBLE-FLOAT quiet NaN>).
   [Condition of type FLOATING-POINT-INVALID-OPERATION]
```

Based on [this issue](https://bugs.launchpad.net/sbcl/+bug/1909881), it seems like my latest error is related to Portacle using an older version of SBCL. I'm closing this issue because this is clearly not related to Coalton. I'm happy to spend my time tinkering with Coalton on Linux. Thanks again.

**Comment by HM0880** [comment]
Commenting to say that I had the same issue "SINGLE-FLOAT-NAN" on Debian with SBCL v1.4.16.  `(ql:system-apropos "float-features")` showed a version of `float-features` from January 2021.

I built SBCL v2.1.9 from source, removed the old Quicklisp directory (by simply renaming to "quicklisp-backup"), and reinstalled Quicklisp from scratch.  Then `(ql:quickload :coalton)` worked perfectly.  Float-features is now `float-features-20210228-git`.

**Comment by stylewarning** [comment]
@HM0880 in your live Lisp image, what does
```
(asdf:system-relative-pathname :float-features "")
```

give you?

**Comment by HM0880** [comment]
@stylewarning 

```
* (asdf:system-relative-pathname :float-features "")
#P"/home/hm/quicklisp/dists/quicklisp/software/float-features-20210228-git/"
```
