### ISSUE TITLE
Replace reliance on `uiop:version<` in `coalton.asd` with `sb-ext:assert-version->=`

### ISSUE THREAD

**Issue by gefjon** [coalton-lang/coalton#1320]
See discussion on the sb-devel mailing list under "freeze for sbcl-2.4.10". I believe you want to replace the conditional in coalton.asd with approximately:

```lisp
#+sbcl
(handler-bind ((error (lambda (c) (push :pre-2-2-2 *features*))))
  (sb-ext:assert-version->= 2 2 2))
```

You may also decide that it's at this point prudent to just rip out support for pre-2.2.2 SBCL, as I imagine >= 2.2.2 versions have proliferated reasonably well by this point. YMMV.

**Comment by csrhodes** [comment]
You'll probably want either `(continue c)` in the handler, or to use `handler-case` rather than `handler-bind`, to actually handle the error.  (Sorry, I wrote in haste yesterday).  Thanks!

**Comment by stylewarning** [comment]
We'll fix it in the next day or so. Thanks for bringing it to our attention.

**Comment by stylewarning** [comment]
Should be fixed, thanks to @garlic0x1. Sorry if it caused any drama on the list. CC @csrhodes
