### ISSUE TITLE
Allow `progn` forms in coalton-toplevel

### ISSUE THREAD

**Issue by Jason94** [coalton-lang/coalton#1330]
Currently `progn` forms aren't allowed inside of `(coalton-toplevel ...)` calls. This makes intuitive sense, but it makes some  macro techniques more inconvenient in Coalton. Macros can only return one form, so if you want to define a macro that, for example, creates multiple functions in CL, you'd just wrap them in a progn. For example:

```lisp
(defmacro make-add-sub-fns (n)
  `(progn
      (defun add-my-n (x) (+ x ,n))
      (defun sub-my-n (x) (- x ,n))))
```

In Coalton you could do the same thing by wrapping them in a `coalton-toplevel`, but then you'd have to place that macro call outside of a coalton-toplevel block. You might want to place the above macro near where `n` is defined, for example, or macros that derive instances near where the type is defined. I think it would be nice to allow `progn` blocks inside of coalton-toplevel, so long as all the forms inside of them were valid toplevel forms.

I don't know much about `.coal` files (haven't used them yet), but this would be a bigger issue if there's no way to workaround this in those files.

**Comment by garlic0x1** [comment]
seems to work for me unless I am misunderstanding something

```lisp
COALTON-USER> (cl:defmacro defadders (x)
                `(progn 
                   (define (addx n) (+ n ,x))
                   (define (subx n) (- n ,x))))
DEFADDERS
COALTON-USER> (coalton-toplevel 
                (defadders 3))
; No values
COALTON-USER> (coalton (addx 2))
5 (3 bits, #x5, #o5, #b101)
```

**Comment by Jason94** [comment]
Ah, it does work. Sorry! I thought I tested it and it didn't work - might have been on an older version or could be misremembering.
