### ISSUE TITLE
What is the difference between Coalton and Shen?

### ISSUE THREAD

**Issue by ghosthamlet** [coalton-lang/coalton#139]
Coalton is a wonderful project.
Shen is also a statically typed functional programming language base on LISP: http://www.shenlanguage.org/,  do you compared to it?

**Comment by stylewarning** [comment]
Coalton is a language with a Haskell-like type system, familiar to most functional programmers. Shen uses the sequent calculus.

One of Coalton’s main goals is to interoperate and be embedded in Common Lisp. Shen intends to be an independent language.

Coalton intends to be implemented as a compiler in Common Lisp. Shen aims to be made of simple primitives implementable in any language.

Coalton is developed with real applications in mind. I’m not sure about Shen.

These are just a few things.

**Comment by ghosthamlet** [comment]
Thanks for the detailed answer.

**Comment by stylewarning** [comment]
We've just created the a GitHub Discussions page. Please feel free to post future questions there. :)
