### ISSUE TITLE
Improve CI Caching

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#151]
See [this](https://github.com/coalton-lang/coalton/pull/149#issuecomment-917786782)

**Comment by colescott** [comment]
We should just run this and it should fix any misconfiguration https://40ants.com/ci/

**Comment by eliaslfox** [comment]
Closing this because I don't think CI caching is possible at the moment. SBCL doesn't always recompile code when the macros that defined it changed. We frequently need to blow away caches locally.
