### ISSUE TITLE
refactor `:classname` slot in `constructor-entry`

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#168]
Currently, `:classname` gets bound to the name of the structure that the Coalton type compiles into. Later, in `compile-pattern`, this `:classname` gets spliced into a Trivia `(structure ,classname ,@fields)` pattern.

There are many types, present and future, that will not have a corresponding Lisp structure type. This came up in PR #167 where `Unit` matching was fixed. Indeed, `Unit` has a `cl:symbol` as a representation, and so we can't assign a structure class name for it.

As such, we should refactor this slot to be something else to support other kinds of Lisp objects and patterns.

**Comment by eliaslfox** [comment]
This was fixed by #174
