### ISSUE TITLE
Build failure: :|@@unbound@@| is not of type (OR COALTON-IMPL/CODEGEN::FUNCTION-ENTRY (FUNCTION (T) *))

### ISSUE THREAD

**Issue by gefjon** [coalton-lang/coalton#199]
When compiling Coalton on SBCL 2.1.10.35-669281695 on MacOS 12.0.1 Arm64, I get the following error first from string.lisp, and then again from cell.lisp if I invoke the ACCEPT restart on the string one:

```
The value
  :|@@unbound@@|
is not of type
  (OR COALTON-IMPL/CODEGEN::FUNCTION-ENTRY (FUNCTION (T) *))
   [Condition of type COMMON-LISP:TYPE-ERROR]
```

I did a bit of playing around with string.lisp in the REPL, isolating forms into individual `coalton-toplevel` blocks, and the error seems to occur if and only if `String`'s `Monoid` and `Into` instances are in the same `coalton-toplevel` form. That is, the following change seems to prevent the error:

```
modified   src/library/string.lisp
@@ -64,17 +64,18 @@
   (define-instance (Ord String)
     (define (<=> a b)
       (lisp Ord (a b)
-         (cl:cond
-           ((cl:string> a b) GT)
-           ((cl:string< a b) LT)
-           (cl:t EQ)))))
+        (cl:cond
+          ((cl:string> a b) GT)
+          ((cl:string< a b) LT)
+          (cl:t EQ)))))
 
   (define-instance (Semigroup String)
     (define (<> a b) (concat-string a b)))
 
   (define-instance (Monoid String)
-    (define mempty ""))
+    (define mempty "")))
 
+(coalton-toplevel
   (define-instance (Into String (List Char))
     (define into unpack-string))
```

cheers,
phoebe

**Comment by eliaslfox** [comment]
Hi @gefjon,
Thanks for the bug report. Are you using the latest quicklisp distribution?

**Comment by gefjon** [comment]
I have
```
(ql:dist-version "quicklisp")
"2021-10-21"
```
Also, of possible note, my `sbclrc` does:
```
(proclaim '(optimize (debug 3) (speed 3) (safety 3) (space 1) (compilation-speed 1)))
```

**Comment by eliaslfox** [comment]
Adding `(proclaim '(optimize (debug 3) (speed 3) (safety 3) (space 1) (compilation-speed 1)))` to my `sbclrc` breaks loading Coalton.

**Comment by gefjon** [comment]
That's... upsetting. Downgrading to `(safety 2)` "fixes" it, which means Coalton is relying on non-conformant unsafe behavior, almost certainly caused by an incorrect type declaration.

**Comment by stylewarning** [comment]
just a bunch: I don't think it's an improper declaration (in the sense that the declaration isn't what we intend), but rather that a type check is occurring before a variable is being initialized. (so this uninitialized sentinel is wreaking some havoc)

**Comment by gefjon** [comment]
Unfortunately, from SBCL’s perspective, a variable with an initial value of `:|@@uninit@@|` having a declared type which does not include that value is incorrect. Their manual is quite clear on the subject in section 4.2.3.

The obvious solution is just to make the declared types of globals be `(or (eql :|@@uninit@@|) ITS-REAL-TYPE)`. If efficiency is a concern, you could add `sb-ext:truly-the` declarations around reads from globals. But I’d only do that if you’re really confident in your typechecker.

**Comment by stylewarning** [comment]
I agree it is a type violation. I wasn't saying SBCL was improperly behaving. I was saying that from a logical standpoint, the intended type is correct.

It's not an efficiency concern; it's how recursive functions and values are uniformly dealt with. It's akin to the usual LETREC-binding problem. There's another conflating factor which is compile-time be run-time (via EVAL-WHEN). Splitting definitions, as you did, caused separate EVAL-WHENs to be formed, which allowed variables to get set up in time for SBCL's type checker to not complain. Obviously that shouldn't be needed.

The codegen that emits global bindings probably needs another look-though, and minimal test cases need to be added to the test suite.

**Comment by gefjon** [comment]
I've isolated a pretty good minimal test case:

```
(uiop:define-package #:wrong-defn-order
  (:use #:coalton))
(cl:in-paclage #:wrong-defn-order)

(coalton-toplevel
  (define-type Foo
    Foo))

(coalton-toplevel
  (declare frob (Foo -> String))
  (define (frob foo)
    "foo")

  (define-instance (Into Foo String)
    (define into frob)))
```

Doing `cl:macroexpand-1` on that last `coalton-toplevel` form yields:

```
(COMMON-LISP:PROGN
 (COMMON-LISP:EVAL-WHEN (:LOAD-TOPLEVEL)
   (COMMON-LISP:SETF COALTON-IMPL::*GLOBAL-ENVIRONMENT*
                       (COALTON-IMPL/TYPECHECKER:ADD-INSTANCE
                        COALTON-IMPL::*GLOBAL-ENVIRONMENT* 'INTO
                        #S(COALTON-IMPL/TYPECHECKER:TY-CLASS-INSTANCE
                           :CONSTRAINTS COMMON-LISP:NIL
                           :PREDICATE INTO FOO STRING
                           :CODEGEN-SYM |INSTANCE/INTO FOO STRING|))))
 (COMMON-LISP:PROGN
  (GLOBAL-VARS:DEFINE-GLOBAL-VAR |INSTANCE/INTO FOO STRING| ':|@@unbound@@|)
  (COALTON-IMPL::DEFINE-GLOBAL-LEXICAL FROB ':|@@unbound@@|)
  (COMMON-LISP:DEFUN FROB (FOO-820)
    (COMMON-LISP:DECLARE (COMMON-LISP:IGNORABLE FOO-820)
                         (COMMON-LISP:TYPE FOO FOO-820)
                         (COMMON-LISP:VALUES COMMON-LISP:SIMPLE-STRING
                                             COMMON-LISP:&OPTIONAL))
    "foo")
  (COMMON-LISP:SETF |INSTANCE/INTO FOO STRING|
                      (COMMON-LISP:LOAD-TIME-VALUE (CLASS/INTO FROB)))
  (COMMON-LISP:SETF FROB (COMMON-LISP:LOAD-TIME-VALUE #'FROB))
  (COMMON-LISP:VALUES)))
```

Notice that `(setf |instance/into foo string| (load-time-value (class/into frob)))` reads from `frob` before `(setf frob (load-time-value #'frob))` initializes it. I believe this is not a case of SBCL being overly pedantic about types (as was my first assumption); it looks like the `into` instance for `Foo` actually keeps holding the uninit sentinel after everything is finished loading.

This looks to be caused by `coalton-impl/codegen:codegen-program` unconditionally putting instance definitions before other bindings (lines 102 -- 106 of src/codegen/program.lisp), clobbering source order.
