### ISSUE TITLE
Error when compiling the package with asdf and quicklisp

### ISSUE THREAD

**Issue by philfuchs** [coalton-lang/coalton#202]
I cloned the repository into quicklisp/local-projects/coalton and loaded the `.asd` file with `(asdf:find-system :coalton)`. Quicklisp alone won't find it. After `(ql:quickload :coalton)` I get this error:

```common-lisp
CL-USER> (asdf:find-system :coalton)
#<ASDF/SYSTEM:SYSTEM "coalton">
CL-USER> (ql:quickload :coalton)
To load "coalton":
  Load 1 ASDF system:
    coalton
; Loading "coalton"
.....
; 
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE:
;   
;     Symbol "SINGLE-FLOAT-NAN" not found in the FLOAT-FEATURES package.
;   
;       Line: 148, Column: -1, File-Position: 4355
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/phil/quicklisp/local-projects/coalton/src/library/arith.lisp" {10064014D3}>
......
; 
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE:
;   
;     Symbol "SINGLE-FLOAT-NAN" not found in the FLOAT-FEATURES package.
;   
;       Line: 148, Column: -1, File-Position: 4355
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/phil/quicklisp/local-projects/coalton/src/library/arith.lisp" {1005370533}>
; 
; compilation unit aborted
;   caught 3 fatal ERROR conditions
;   caught 2 ERROR conditions
; Evaluation aborted on #<SB-INT:SIMPLE-FILE-ERROR "~@<Couldn't load ~S: file does not exist.~@:>" {10028353B3}>.
CL-USER> 
```

**Comment by colescott** [comment]
This looks similar to #132 

It is likely that your quicklisp dist has not been updated since FLOAT-FEATURES was last updated. You can update this using `(ql:update-dist "quicklisp")` and it should allow you to load coalton.

**Comment by philfuchs** [comment]
After successfully updating Quicklisp `(asdf:load-system :coalton)` can't seem to find coalton. If I do `(asdf:load-asd "coalton.asd")` and then `(ql:quickload :coalton)` afterwards I get this error:

![image](https://user-images.githubusercontent.com/88037858/141204316-d4a88f34-189b-4cca-9db7-ad37eb1f9603.png)

**Comment by philfuchs** [comment]
I both have a relatively new SBCL (SBCL 2.0.1.debian) and the latest Quicklisp (2021-10-2) and I still get the error. I'll have another look at coalton when it's on quicklisp.

**Comment by stylewarning** [comment]
SBCL 2.0.1 is old, which matters a lot for non-portable features. There have been 21 releases of SBCL since then.

2.1.10 is the latest.

**Comment by philfuchs** [comment]
You're right, the version that I installed via `apt install sbcl` is very outdated... with `2.1.9` via guix it works! Thanks.
