### ISSUE TITLE
CI/CD has spurious "build" requirement

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#212]
I'm not sure why, but automatic testing is being held up by a mysterious 5th status check called "build". It's not allowing PRs to be auto-merged and it's requiring administrator merging. I looked into the YAML and couldn't figure out why.

The 5th status check isn't reported when you hover over the status icon, where it says 4/4 succeeded. It also isn't recorded in the GH Actions dashboard...

**Comment by eliaslfox** [comment]
Does it show up in the merge requirement settings?

**Comment by stylewarning** [comment]
it was a protected branch requirement. fixed.
