### ISSUE TITLE
Add functions for grabbing parts of larger tuples

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#226]

**Comment by stylewarning** [comment]
How are any of these conventions

```
get-i-N
geti.N
geti/N
```

for getting the `i` out of `N` elements?

**Comment by eliaslfox** [comment]
They're all kinda ugly

**Comment by eliaslfox** [comment]
Maybe this should wait until we get syntax for `(.5 x)`

**Comment by stylewarning** [comment]
> Maybe this should wait until we get syntax for `(.5 x)`

The Lisp reader will always read that as a float

**Comment by eliaslfox** [comment]
hmm. we could do `(#5 x)` then

**Comment by stylewarning** [comment]
`#i` is a dispatching reader macro like for `#1=(1 . #1#)` and whatever.

`\.1 == |.1|` works though.

**Comment by eliaslfox** [comment]
I'm assuming it isn't possible to add a reader macro for every number?

**Comment by stylewarning** [comment]
> I'm assuming it isn't possible to add a reader macro for every number?

It is if you make your own read table! It would be on every digit character.

**Comment by colescott** [comment]
This seems to be blocked both on the syntax and the type family/data kind requirements, both of which are not easily solved. Per @eliaslfox 's request I'm going to close this
