### ISSUE TITLE
Optional error message to fromSome

### ISSUE THREAD

**Issue by notmgsk** [coalton-lang/coalton#243]
`fromSome` might be slightly more ergonomic if the error message was optional

```
(fromSome "oh no an error"
  (something-that-returns-none))
```
vs
```
(fromSome (something-that-returns-none))
```
with a default sensible error message about expecting something other than `None`.

With this syntax you could also provide format arguments
```
(define (parse-int-or-fail s)
  "Parse the string S as an integer, or error."
  (fromSome (parse-int s)
    "Failed to parse integer from ~a" s))
```

**Comment by colescott** [comment]
Coalton currently doesn't have support for optional parameters to functions and it isn't possible in the current type system. An alternative in this case is to manually call `unwrap` which will throw a runtime error when it is `None`

**Comment by eliaslfox** [comment]
Unwrapping without arguments is now solved by unwrap.
