### ISSUE TITLE
fold isn't actually tail-recursive

### ISSUE THREAD

**Issue by danielkoning** [coalton-lang/coalton#252]
This might have been introduced by the recent switch to CL-native lists; I'm not sure.

`fold` claims to be tail-recursive in its docstring, but it isn't:

```
COALTON-USER> (coalton
               (fold + 0
                     (lisp (List Integer) ()
                       (cl:loop :repeat 10000000 :collect 1))))
Control stack guard page temporarily disabled: proceed with caution
; Debugger entered on #<SB-KERNEL::CONTROL-STACK-EXHAUSTED {1003640FD3}>
```

(You can't even get the `length` of a long list, because `length` is implemented using `fold`.)

**Comment by danielkoning** [comment]
This resolves in SBCL if you `(declaim (optimize (speed 1)))` or higher. But it isn't getting compiled that way by default, not for me at least.

**Comment by eliaslfox** [comment]
This instance could be solved by having fold call out to `cl:reduce`. It looks like there are SBCL specific optimize flags for enabling TCO[^1]. We could emit these for all Coalton code.

[^1]: [https://0branch.com/notes/tco-cl.html#sec-2-2-2](https://0branch.com/notes/tco-cl.html#sec-2-2-2)

**Comment by eliaslfox** [comment]
```
; caught COMMON-LISP:STYLE-WARNING:
;   The policy SB-C::MERGE-TAIL-CALLS has been deprecated as of SBCL version 1.0.53.74.
;   
;   In future SBCL versions SB-C::MERGE-TAIL-CALLS will signal a full warning at
;   compile-time.
;   See also:
;     The SBCL Manual, Node "Deprecation Conditions"
```

It looks like merge tail calls is deprecated.

**Comment by stylewarning** [comment]
SBCL maintainer says TCE is "always on", but DEBUG=3 adds debug code that wraps tail-calls (thus making them not).

**Comment by eliaslfox** [comment]
I'm closing this. It doesn't seem like something we can fix.
