### ISSUE TITLE
Possible infinite macro-expansion

### ISSUE THREAD

**Issue by christophejunke** [coalton-lang/coalton#257]
Function `parse-application` in `src/ast/parse-form.lisp` calls `macro-function` on a symbol that is the head of a Coalton function application and applies the macroexpansion. I spotted this case out of habit of writing `(lambda ...)` instead of `(fn ...)`, where the form expands as `(function (lambda ...))`, which results in infinite recursion.

This is not really a bug since `lambda` is not part of the Coalton language, but on the other hand there should ideally be a better error  message than reaching Control Stack Exhausted.

There could be a general mechanism to guard against infinite recursions (e.g. limit depth (simple), or check if there is a repetitive pattern in the expansion (harder)) 

Also, macroexpansion is done for arbitrary symbols, maybe symbols from the CL package should not be expanded (they tend to produce non-Coalton code anyway). Or only symbols marked as being Coalton macros should be expanded.

I am opening this issue to discuss possible options before suggestion a pull request.

**Comment by eliaslfox** [comment]
I think a depth limit sounds like a reasonable solution.

**Comment by eliaslfox** [comment]
I'm also a fan of not expanding macros in `cl:`. That way we can generate much better error messages when someone uses `lambda`.

**Comment by stylewarning** [comment]
We might also call the CL macroexpander instead of walking ourselves.
