### ISSUE TITLE
Attempt to build failed: 

### ISSUE THREAD

**Issue by chebert** [coalton-lang/coalton#314]
I just cloned coalton, and tried to (ql:quickload :coalton), but it looks like the float-features package coalton uses might be a different version than what I have access to.
I have a folder titled float-features-20201220-git (I think that 20201220 is the version id).

Below is the output:

> (ql:quickload :coalton)
To load "coalton":
  Load 1 ASDF system:
    coalton
; Loading "coalton"
..........
; 
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE:
;   
;     Symbol "SINGLE-FLOAT-NAN" not found in the FLOAT-FEATURES package.
;   
;       Line: 181, Column: 46, File-Position: 5463
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file <>\\quicklisp\\local-projects\\coalton\\src\\library\\arith.lisp" {100ACEEC63}>
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
...........
; 
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE:
;   
;     Symbol "SINGLE-FLOAT-NAN" not found in the FLOAT-FEATURES package.
;   
;       Line: 181, Column: 46, File-Position: 5463
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file <>\\quicklisp\\local-projects\\coalton\\src\\library\\arith.lisp" {10069BEB73}>
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition

**Comment by stylewarning** [comment]
We've seen this issue before and I think it's because your SBCL is too old.

**Comment by stylewarning** [comment]
See [this issue](https://github.com/coalton-lang/coalton/issues/132) thread.
