### ISSUE TITLE
sqrt and some transcendental functions not implemented

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#366]
sqrt, exponentiation, exp, log, sin, cos, tan, their inverses, etc. aren't implemented. Binding to Lisp isn't the hard part, but coming up with a good standard library design is.

**Comment by HM0880** [comment]
I would be interested in handling this issue.  I was working on transcribing your great post about using typeclasses for a simple graphics library [1].  I got the error "Unknown binding COS", so I searched the Coalton issues for Math(TM) and found this issue.

Do you have thoughts on a good standard library design?  We can discuss here or on the Discord chat.


P.S. Once the simple graphics library is working, I will contribute the Coalton version to the "small Coalton programs" examples [2].


[1] https://coalton-lang.github.io/20211212-typeclasses/
[2] https://github.com/coalton-lang/coalton/tree/main/examples/small-coalton-programs

**Comment by stylewarning** [comment]
CC @aijony who has been thinking about it.

**Comment by aijony** [comment]
I haven't put too much thought into, as so much as I just ripped off Haskell's [Floating](https://hackage.haskell.org/package/base-4.8.2.0/docs/src/GHC.Float.html#Floating). It seems like an okay design and I think the naming (i.e. `log`, `logBase`, `**`) is reasonable too considering `expt` is already taken for integers in Coalton and `log` in both Haskell and Lisp are base e. However, I am somewhat just appealing to authority here - I'd love to hear other thoughts.

Also when thinking about Lisp interop, the functions are complex so #407 could come in handy.

**Comment by eliaslfox** [comment]
I think Floating seems like a reasonable design. `expt` and other currently monomorphic functions could be moved to type class methods.

**Comment by HM0880** [comment]
@aijony Can you link to the file(s) that have your version of Haskell's /floating/?  I checked both the Coalton main repo and your fork, and I could not find files that looked related to floating.

Also, do you imagine binding to all of the `define-number-stuff` types listed in [1]?

[1] https://github.com/coalton-lang/coalton/blob/main/src/library/arith.lisp#L164

**Comment by aijony** [comment]
@HM0880 Here is Floating as one big class: https://gist.github.com/aijony/b86dd0684e21c7a4e953ee66eda1ed33
