### ISSUE TITLE
Coalton Intro doc still references the Show typeclass, even though it is no longer in the stdlib

### ISSUE THREAD

**Issue by Gira-X** [coalton-lang/coalton#379]
If I compile this with the current `main` branch:

```lisp
(coalton-toplevel
 (declare f (Integer -> Integer -> String))
  (define (f x y)
    (progn
      (let x_ = (show x))
      (let y_ = (show y))
      (concat-string x_ y_))))
```

I get this error:

```
Unknown binding show
in definition of x_
in definition of f
in COALTON-TOPLEVEL
```

I suppose `(show)` converts something to a string?

**Comment by stylewarning** [comment]
I think `show` was deleted because we wanted a better solution for integrating with the Lisp pretty printer, but the intro doc wasn't updated... Sorry about that, the doc should get updated.

**Comment by stylewarning** [comment]
Indeed, this was the commit that removed the `Show` type class: https://github.com/coalton-lang/coalton/commit/5b64540385c102bfec6b3e4ffaa281e8810e7052

You're right, `show` used to convert a value to a visually useful string representation.

**Comment by Gira-X** [comment]
I came up with this after reading about the Coalton-Lisp interop, just as a quick way to get the example code to work as it should (it's some of my first Coalton code, there is probably a better way to do this):

```lisp
(coalton-toplevel
  (declare show (:a -> string))
  (define (show x)
    (lisp string (x)
      (cl:format nil "~a" x))))
```

**Comment by stylewarning** [comment]
That's definitely a completely reasonable hack to get it working!
