### ISSUE TITLE
Let Flattening

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#40]
Let bindings tend to form a dependency chain in real code. This will create a series of dependent sccs which will then be codegened into a series of nested let expressions. 

These sccs could be flattened into a smaller number of sccs which will then generate less code.

**Comment by eliaslfox** [comment]
I no longer consider this a priority.

**Comment by stylewarning** [comment]
Is it still useful to do? Maybe a `low-priority` tag?

**Comment by eliaslfox** [comment]
I don't think so. We aren't generating super nested code with long compile times anymore.
