### ISSUE TITLE
Matching on uncalled 0-arity constructors will short-circuit

### ISSUE THREAD

**Issue by aijony** [coalton-lang/coalton#494]
If you don't wrap your constructors with parens, the match statement will short-circuit. This should either work or at least result in an error:
```
(coalton
 (match False
        (True 1)
        (False 2)))
 ;; => 1
```

**Comment by aijony** [comment]
I'll admit it didn't even click for me that warning was related to this issue. I probably could have figured it out if I took the word "warning" more seriously. However it seems like a fairly subtle way to trip up on what seems like intuitive syntax (i.e. `(coalton (False))` is invalid). I guess this is just the price one pays for not having case sensitivity #73.

Now that I better understand the issue, I can't think of a great solution (except for me to drink more coffee). I'll close the issue unless someone has any ideas.

**Comment by stylewarning** [comment]
One "solution" would be to make capturing bindings explicit with, say, an @ sign or something. That way variables pay the cost for use, not constructors.
