### ISSUE TITLE
fromSome is annoying

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#497]
It's really annoying to always pass a string to fromSome. I wish it just had its own error message.

**Comment by eliaslfox** [comment]
Like [`unwrap`](https://github.com/coalton-lang/coalton/blob/main/library/classes.lisp#L295)?

**Comment by stylewarning** [comment]
> Like [`unwrap`](https://github.com/coalton-lang/coalton/blob/main/library/classes.lisp#L295)?

Yes! Forgot about it.

(See also #243)
