### ISSUE TITLE
Allow docstrings in `define-instance` forms

### ISSUE THREAD

**Issue by ornamentist** [coalton-lang/coalton#524]
Docstrings are useful first-class documentation for various forms in Coalton, including `define`, `define-type`, and `define-class`. Currently the `define-instance` form does not allow a docstring. 

Would it be feasible (and practical) to allow docstrings in these forms?  

They won't *always* be needed, but sometimes I find myself using `;;`  comments before the `define-instance` form to highlight caveats or issues with the instance and a docstring could capture these notes.

An example:

```
(define-instance (Eq Symbol)
  "Note anything unusual or unexpected about Symbol instances of Eq."

  (define (== a b)
    "Test two symbols for equality."
    (== (symbol-name a) (symbol-name b))))
```

**Comment by eliaslfox** [comment]
It's definitely feasible syntactically. We could render this alongside instances in the html doc like Haskell does. See the documentation on `Eq Double` for an example https://hackage.haskell.org/package/base-4.16.1.0/docs/Data-Eq.html.

In the repl we could do something like:
```
COALTON-USER> (documentation :instance (Eq Symbol))
   Note anything unusual or unexpected about Symbol instances of Eq.
  
    == :: Symbol -> Symbol -> Boolean
      Test two symbols for equality
```

**Comment by eliaslfox** [comment]
This is now implemented but it instance documentation isn't visible in the doc generator.
