### ISSUE TITLE
1+ and 1- still calling fromInt

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#545]
The stdlib functions `1+` and `1-` are still calling `fromInt` on the value `1`, which means it'll get double-wrapped to `(fromInt (fromInt 1))`. Just remove the `fromInt`s and it should be OK (and also audit the rest of the stdlib for these unnecessary calls).

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue
