### ISSUE TITLE
there needs to be a way to pass Lisp variables into COALTON forms

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#577]
The `coalton` macro in Lisp is of extremely limited utility if there's no way to pass Lisp objects into it.

**Comment by eliaslfox** [comment]
What's wrong with
```
(coalton (+ (lisp () Integer my-package:*my-var*) 5))
```

**Comment by stylewarning** [comment]
@eliaslfox I didn't even think to do that. 🙄
