### ISSUE TITLE
Optimize curried top-level function applications

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#631]
Right now, suppose we have

```
(define (f x1 x2 ... xn) ...)
```

Then the call

```
(f a1 a2 ... ak)
```

for `k < n` will allocate `k` intermediate closures.

We already optimize the case when the call is fully saturated (i.e., `k = n`).

This issue concerns itself with optimizing top-level functions getting called (not local functions getting called).

**Comment by karlosz** [comment]
Let's break down what is actually suboptimal with the current partial application implementation:

If we partially apply a function entry object `f` (representing a first class Coalton function use) of arity `N` with `M` (< N) arguments, the way we represent function entry objects now means that this partial application is done by calling a nested Lisp lambda repeatedly. This means we currently end up having to do `M` function calls and `M` closure environment allocations to unpeel each layer of nesting. The resulting closure, `f_p`, when supplied with the remaining `M - N` arguments, still has to partially apply away the arguments one-by-one. The only time the saturation optimization kicks in at the moment is when the original function entry object `f` is supplied all of its arguments, and is never used for the intermediate partially applied functions.

I think we could avoid the unpeeling all together by modifying the `FUNCTION-ENTRY` structure to contain more entry points and ditching the direct use of Lisp lambdas.
