### ISSUE TITLE
Data-Letrec doesn't work in Coalton form

### ISSUE THREAD

**Issue by rvs314** [coalton-lang/coalton#679]
When I use data letrec in a toplevel definition, it works as expected:

```lisp
(coalton-toplevel
  (define foo
    (let ((a (cons 0 a)))
      a)))

(coalton foo) ; => #1=(0 . #1#)
```

However, a seemingly equivalent operation fails:

```lisp
(coalton
  (let ((a (cons 0 a)))
    a))

; caught COMMON-LISP:WARNING:
;   undefined variable: GRAMMAR-COMPRESSION::A-767
```

@gefjon @eliaslfox - is there a reason for this? Let me know if I'm just using it wrong or if this is an actual bug.

**Comment by eliaslfox** [comment]
This looks like a bug

**Comment by gefjon** [comment]
The `coalton` macro must be in some way calling a different codegen function than `coalton-toplevel` uses to generate expressions. This is a bug.
