### ISSUE TITLE
intro-to-coalton example of error on heterogenous list does not throw error

### ISSUE THREAD

**Issue by shukryzablah** [coalton-lang/coalton#725]
The following code does not throw the expected error: 

```lisp
(coalton-toplevel
  (define wut (make-list 1 2 3.0)))
```

<img width="746" alt="Screen Shot 2022-08-28 at 11 30 45 AM" src="https://user-images.githubusercontent.com/28762146/187082030-d3dcf1d9-43d2-42fc-9005-3f5ecee596e5.png">

The [intro-to-coalton document](https://github.com/coalton-lang/coalton/blob/main/docs/intro-to-coalton.md) says twice that lists have to be homogenous.

I'm at HEAD b7c028d

**Comment by gefjon** [comment]
Lists do have to be homogeneous, but integer literals are coerced (by `fromInt`) into any `Num` type. You have constructed a homogeneous list of floats.
