### ISSUE TITLE
Coalton defaults to `Integer` too early

### ISSUE THREAD

**Issue by colescott** [coalton-lang/coalton#747]
The following code should allow me to construct a `Vector IFix`:
```
(coalton-toplevel (define x (the (Vector IFix) (into (make-list 42)))))
```
Instead, I receive the error `Unknown instance for predicate INTO (LIST INTEGER) (VECTOR IFIX)` which indicates that Coalton is defaulting the `make-list` form to `List Integer` too early.

**Comment by stylewarning** [comment]
Is it true that it's really doing it too early? I'd think that it's non-intuitive, but since `Into :a :b` is multi-parameter and unconstrained, Coalton isn't compelled to unify `:a` and `:b` in any way.

**Comment by eliaslfox** [comment]
@stylewarning is correct. This is the expected behavior
