### ISSUE TITLE
`foreach` functions should require their callback to return `Unit`

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#755]

**Comment by gefjon** [comment]
why?

**Comment by stylewarning** [comment]
> why?

this is discussed in the PR that fixed it

**Comment by gefjon** [comment]
Having seen the explanation (which, for posterity, is that if you accidentally pass a curried two-argument function to `for-each` or similar, it will silently be partially applied and the resulting closure discarded, leading to hard-to-detect bugs), I support this change. I also wonder how difficult it would be to replicate Rust's `#[must_use]` attribute, which allows the compiler to signal a warning when the results of certain functions are discarded. It would be pretty slick to be able to issue a warning any time someone partially applies a function and discards the result.
