### ISSUE TITLE
Add identifier type

### ISSUE THREAD

**Issue by eliaslfox** [coalton-lang/coalton#764]
Most lisp type declarations of `symbol` should be `(and symbol (not null))`

**Comment by gefjon** [comment]
I believe you want `(not boolean)` rather than `(not null)`. Also, Some, but not all, should be `(and symbol (not boolean) (not keyword))`

**Comment by stylewarning** [comment]
Should it really be `(and symbol (not cl symbol) (not keyword symbol)!`?
