### ISSUE TITLE
Support other lisp implementations

### ISSUE THREAD

**Issue by chrisdone-artificial** [coalton-lang/coalton#778]
> While we try to be ANSI-conforming, Coalton may only work on SBCL 2.1.x.

If I were to try to use Coalton on LispWorks or ECL, for example, how much trouble would I encounter? Alternatively, how much work would it be to make it just depend on the CL standard?

My other car is a cdr @chrisdone

**Comment by stylewarning** [comment]
Right now there are some SBCL-specific things we rely on. There's not much (e.g., custom hash tables); most of the code is ANSI enough.

We are actually currently making a push to identify all of those areas and rectify them.

Our ultimate goal is to have CI testing against at least one other Lisp besides SBCL.

**Comment by chrisdone** [comment]
Neat, thanks!

**Comment by eliaslfox** [comment]
As of #780 Coalton now builds on Allegro. @colescott and I attempted to get Coalton running on other lisp implementations and we ran into the following issues:

* ECL: Attempting to compile [library/types.lisp](https://github.com/coalton-lang/coalton/blob/main/library/types.lisp) caused a segfault.

* Clasp: The compiler errors at runtime, the issue appears to be a miscompile of a `(declare (values ...))` annotation. Values declarations are not standard lisp and Clasp seems to ignore them by default. However, in at least one case it is compiled to `(typep x 'values)` which errors at runtime.

* Clisp doesn't support package local nicknames. There is a pr, but it's unmerged https://gitlab.com/gnu-clisp/clisp/-/merge_requests/3
 
* CCL appears to use fpu traps internally which breaks math on NaN values.

* ABCL compiles [library/types.lisp](https://github.com/coalton-lang/coalton/blob/main/library/types.lisp), but then it appears to generate an invalid fasl file which it fails to load.

I haven't had a chance to try LispWorks yet.

**Comment by gmpalter** [comment]
You can use `(ccl:set-fpu-mode :overflow nil :underflow nil :division-by-zero nil :invalid nil :inexact nil)` to disable traps

**Comment by eliaslfox** [comment]
@gmpalter masking float traps works, thank you.

**Comment by eliaslfox** [comment]
Closing as CCL and Allegro are now running in CI.
