### ISSUE TITLE
Equivalent of abbreviating type specifiers in COALTON

### ISSUE THREAD

**Issue by digikar99** [coalton-lang/coalton#787]
I'm not sure if I missed something in the documentation-so-far and examples, but I wanted to know how to express a type that denotes the integer/real-number 1, or the integer range, say from -1 to 1? Or, if this is not possible, could someone point to any research pertaining to this, eg: HM extensions for "what is the term for this in papers"?

---

Justifying the title: CLHS reference - http://clhs.lisp.se/Body/01_ddfa.htm

> An ``abbreviating'' [type specifier](http://clhs.lisp.se/Body/26_glo_t.htm#type_specifier) is one that describes a [subtype](http://clhs.lisp.se/Body/26_glo_s.htm#subtype) for which it is in principle possible to enumerate the [elements](http://clhs.lisp.se/Body/26_glo_e.htm#element), but for which in practice it is impractical to do so.

For example, [integer](http://clhs.lisp.se/Body/t_intege.htm) is called an abbreviating compound type specifier.

**Comment by stylewarning** [comment]
Coalton (or HM) don't have mechanisms for supporting types with variable bounds/ranges. That's not something that can be statically deduced.

**Comment by digikar99** [comment]
> Coalton (or HM) don't have mechanisms for supporting types with variable bounds/ranges.

I see. But do you (or any readers) know of HM extensions that allow for this? A simple search turns up results for HM extensions with subtyping, HM extensions with coercive subtyping, but I couldn't find anything on bounds/ranges.

> That's not something that can be statically deduced.

Are there examples where this runs into problems? I can imagine that a value, say 1, can first be represented as `(eql 1)` which can then be type checked against the `(integer low high)` type specified by the user. Is it the "specified by the user" that is the problem, or something else?

**Comment by eliaslfox** [comment]
My guess is that you want dependent types. If integers are typed as ranges then ideally the type of additions would be something like:
```
+ :: (integer low high) -> (integer low high) -> (integer (low + low) (high + high))
```
There's ways to do stuff like this with typelevel numbers but the general case requires dependent types. See [Idris](https://github.com/idris-lang/Idris2) and [this example of vector length](https://idris2.readthedocs.io/en/latest/tutorial/typesfuns.html#vectors).

**Comment by digikar99** [comment]
> dependent types

Thanks, this looks relevant! And yes, searching about this does suggest that something like this can be emulated with HM/Coalton, but it seems to require [a special case for each such type](https://www.cambridge.org/core/journals/journal-of-functional-programming/article/do-we-need-dependent-types/374DA8854D388E986FE35859390C1C4D).
