### ISSUE TITLE
Naming of `is*` functions

### ISSUE THREAD

**Issue by fosskers** [coalton-lang/coalton#804]
I noticed these functions in the docs:
![issome](https://user-images.githubusercontent.com/229679/213381183-c114685b-aeb8-4291-9832-39e4078d2f39.png)
![isok](https://user-images.githubusercontent.com/229679/213381199-b4b27b6a-535d-466b-b2c8-c30a5e497940.png)
These names seem likely to have been lifted directly from Rust, but perhaps it would be more Lispy to name them `some?` etc.?

**Comment by stylewarning** [comment]
You are correct. The standard library needs a run-through to be made consistent against our evolving style guide. https://github.com/coalton-lang/coalton/blob/main/docs/style-guide.md
