### ISSUE TITLE
Howto : how to define/declare a list of a structure

### ISSUE THREAD

**Issue by devosalain** [coalton-lang/coalton#821]
How to define a structure & define a list of this structure, with the imperative requirement that this list can only contain elements of this specific structure and nothing else, checked at compile-time.

**Comment by stylewarning** [comment]
```
(define-type Foo
  (Foo Integer String))

(declare bar ((List Foo) -> Foo))
(define (bar l)
  ...)
```

**Comment by devosalain** [comment]
Ooh I see. List is a keyword ( & comparable to ocaml who uses " List of " )

**Comment by stylewarning** [comment]
> Ooh I see. List is a keyword ( & comparable to ocaml who uses " List of " )

List is just a normal type built in to the standard library, not a keyword! You could have defined it like:

```
(define-type (My-List :t)
  My-Nil
  (My-Cons :t (My-List :t)))
```

:)
