### ISSUE TITLE
How to change to  value  of a variable (mutable state) in coalton

### ISSUE THREAD

**Issue by devosalain** [coalton-lang/coalton#822]
```
(load "~/quicklisp/setup.lisp")
(declaim (optimize (speed 3) (safety 3)))
(ql:quickload "fiasco")
(ql:quickload "coalton")
(defpackage mytest
  (:use #:coalton #:coalton-prelude)
  (:export cmain ) );defpackage
(in-package :mytest)
(coalton-toplevel
    (define  retval "Initial")
    (define  (modify-retval  ())
		(set retval "Modified")
        Unit
      )
    ;Error -> Unknown  binding SET...,COMMON-LISP:SET...
```
I tried a lot of things in the function modify-retval but all set & cl:set failed with unknown binding.
(So  i need set! )

**Comment by gefjon** [comment]
Coalton bindings are immutable. If you want a mutable place, you need to use `Cell`, provided by the `coalton-library/cell` package.

```
(defpackage #:mytest
  (:use #:coalton #:coalton-prelude)
  (:local-nicknames (#:cell #:coalton-library/cell)))
(in-package #:mytest)
(coalton-toplevel
  (define retval (cell:new "Initial"))
  (define (modify-retval)
    (cell:write! retval "Modified")
    Unit))

**Comment by devosalain** [comment]
Thanks , but can you give me a documentation reference ?

**Comment by gefjon** [comment]
https://coalton-lang.github.io/reference/#coalton-library/cell-package

**Comment by devosalain** [comment]
A library  reference  is the last place a mortal being like me looks.

**Comment by stylewarning** [comment]
> A library  reference  is the last place a mortal being like me looks.

Maybe you could contribute a section on mutation/mutability of variables here? https://github.com/coalton-lang/coalton/blob/main/docs/intro-to-coalton.md

**Comment by devosalain** [comment]
If I would have the knowledge & intelligence I would contribute. But currently I'm fighting the type system.
Nothing wrong with the type system. Even opposite. But  the docs lack.
