### ISSUE TITLE
How to "wrap" a function returning a string when called from coalton

### ISSUE THREAD

**Issue by devosalain** [coalton-lang/coalton#823]
```
(load "~/quicklisp/setup.lisp")
(declaim (optimize (speed 3) (safety 3)))
(ql:quickload "fiasco")
(ql:quickload "coalton")

(defpackage mytest
  (:use #:coalton #:coalton-prelude)
  (:export cmain callouterprint) );defpackage

(in-package :mytest)

(cl:defun innerprint (s)
  (cl:print s))

(cl:defun returnhello ()
  "Hello1"
  )

(coalton-toplevel
    (define  ctext "Hello World")

    (declare outerprint ( String -> Unit ))
    (define (outerprint s)
        (lisp Unit (s) (innerprint s) Unit))

    (declare cmain ( Unit -> Unit ))
    (define (cmain ()) (outerprint ctext) )

    (declare callouterprint (Unit -> Unit))
    (define (callouterprint ())
        (outerprint "Hello2")
        (outerprint (lisp  Unit () (returnhello) Unit ))
      ;Wrapper  Error  -> type Error ......................................................................
      ; What's wrong ???????????????????????????????????
        Unit
      );define
    );coalton
(in-package :cl)
(defun main ()
	(mytest:cmain coalton:Unit )
    (mytest:callouterprint coalton:Unit ))

(sb-ext:save-lisp-and-die "test.exe" :toplevel #'main :executable t)
```

**Comment by gefjon** [comment]
The `lisp` form's syntax is `(lisp RETURN-TYPE (&rest COALTON-CAPTURES) &body LISP-FORMS)`, where:

- RETURN-TYPE is a Coalton type, which you are asserting is the return type of the LISP-FORMS.
- COALTON-CAPTURES are Coalton variables which will be made visible within the LISP-FORMS.
- LISP-FORMS is any number of Common Lisp expressions. The primary return value from evaluating the last expression *must* be of type RETURN-TYPE, and will be used as the return value of the `lisp` form.

So, when you write

```lisp
(lisp Unit () (returnhello) Unit)
```

you are saying, "This is a sequence of Lisp expressions which return `Unit` and reference no Coalton variables. First, call the Lisp function `returnhello` with no arguments. Then, return `Unit`."

The `lisp` form you want to write in this case is:

```lisp
(lisp String () (returnhello))
```

which means "This is a sequence of Lisp expressions which return a `String` and reference no Coalton variables. Call the lisp function `returnhello` with no arguments and return its primary value."

I'll also add that if you want to pass arguments to a Lisp function, the way to do that probably looks like:

```lisp
(defpackage #:cl-parts
  (:use #:cl)
  (:export #:format-to-string-aesthetic))
(in-package #:cl-parts)

(defun format-to-string-aesthetic (thing)
  (format nil "~a" thing))

(defpackage #:coalton-parts
  (:use #:coalton #:coalton-prelude))
(in-package #:coalton-parts)

(coalton-toplevel
  (declare format-to-string-aesthetic (:a -> String))
  (define (format-to-string-aesthetic thing)
    (lisp String (thing)
      (cl-parts:format-to-string-aesthetic thing))))
```

**Comment by devosalain** [comment]
Thanks, I have the feeling I fight Coalton.  
And  not because Coalton in itself is  bad, but because of  lack of good documentation.

**Comment by stylewarning** [comment]
> Thanks, I have the feeling I fight Coalton.  
> 
> And  not because Coalton in itself is  bad, but because of  lack of good documentation.

The project is still in development. We certainly find documentation important, and we certainly have plans to flesh it out, but currently the general language UX (like good error messages, a consistent standard library, requisite type system features) is higher priority than painstakingly documenting everything that's here now. Nonetheless, it's work that will get done in due time.

With that said, we have the standard library reference, as well as some [introductory docs](https://github.com/coalton-lang/coalton/tree/main/docs). We welcome pull requests if you have ways of making the docs more useful or readable.

My recommendation isn't to approach Coaltonhy just guessing. Instead, read the existing docs, look at the standard library for examples, and peruse the reference docs. While it's not all nice and sweetly packaged for rapid learning, Coalton is a small enough language that an afternoon or two should be sufficient to wrap your head around every construct it has to offer, if approached by way of the above method.

Thanks for the feedback. It is
meaningful to us.
