### ISSUE TITLE
Recursive `let` binding of `(the (:a -> :b) (fn (a) ...))` disallowed by new frontend

### ISSUE THREAD

**Issue by gefjon** [coalton-lang/coalton#833]
The new parser rejects e.g.

```
(coalton-toplevel
  (declare add-slowly (UFix -> UFix -> UFix))
  (define (add-slowly a b)
    (let ((loop (the (UFix -> Unit)
                     (fn (n)
                       (when (math:positive? n)
                         (loop (1- n)))))))
      (loop (+ a b))
      (+ a b))))
```

which was accepted previously. The specific error is:

```
error: Invalid recursive bindings
  --> COALTON-TOPLEVEL (/private/var/tmp/slimeIxmdPU):3:9
   |
 3 |    (LET ((LOOP
   |           ^^^^ invalid recursive variable bindings
   [Condition of type SB-INT:COMPILED-PROGRAM-ERROR]
```

Fixing this should be relatively simple; I believe one just needs to edit the definition of `binding-function-p` in src/binding/function.lisp to recurse into `node-the`.

**Comment by gefjon** [comment]
I was playing around a little with this, and I assumed recursive data was broken too, so I tried adding a file `tests/parser/parse-let.good.2.coalton` (with `*.1.*` being a recursive `let` of a `the ... (fn ...)`), containing:

```
;; GOOD: Parse recursive let of `the ... (Cons ... ...)`
(package test-package)

(define foo
  (let ((circle (the (List Integer)
                     (Cons 0 circle))))
    circle))
```

With that file, `(fiasco:run-tests 'coalton-tests::test-parser)` succeeded. But when I pasted the `define foo` form into a scratch buffer inside a `coalton-toplevel` and compiled it with `C-c C-c`, I got a parse error. Is there some difference between the `read-program` parser and whatever gets called by `coalton-toplevel`?

**Comment by gefjon** [comment]
Apparently also broken, with a less obvious fix: I have a macro that expands into a `let` that sometimes introduces no bindings. This gets treated as `(let cl:nil ...)`, which is rejected by the parser.

**Comment by eliaslfox** [comment]
`(let cl:nil ...)` should be accepted, I'll fix that.

> Is there some difference between the read-program parser and whatever gets called by coalton-toplevel

The parser tests just test the parser. If you put that in a `coalton-toplevel` it fails during type checking.

The `the` checks should be an easy fix, we just need to special case it in some checks.

**Comment by gefjon** [comment]
> The parser tests just test the parser. If you put that in a coalton-toplevel it fails during type checking.

Ah, makes sense!

> The the checks should be an easy fix, we just need to special case it in some checks.

I have a fix for the `fn` case already, just figuring out how to handle the constructor case and where to put tests.
