### ISSUE TITLE
Document the `coalton-testing` API for defining test suites, and ASDF integration

### ISSUE THREAD

**Issue by gefjon** [coalton-lang/coalton#871]
Once we start playing with ASDF integration, we'll probably want to define a `system` subclass `coalton-testing-system`, but for now it'd be good to document what we have.

**Comment by Izaakwltn** [comment]
Documentation handled in merged request #874, should this issue close or stay open for the `coalton-testing-system` potentiality?

**Comment by eliaslfox** [comment]
Resolved in #874
