### ISSUE TITLE
should `(define (f _) _)` be valid?

### ISSUE THREAD

**Issue by stylewarning** [coalton-lang/coalton#872]
is `_` for all intents and purposes still just a valid (ignorable) symbol, but can still be used as a lexical variable?

**Comment by eliaslfox** [comment]
Currently yes it is. Once #865 is resolved, it'll be a wildcard pattern and not bind a variable. 

Once that happens I think we should ban `_` as a variable name.

**Comment by stylewarning** [comment]
Likewise, `(define (f _ _) ...)` will become valid syntax
