### ISSUE TITLE
Reader is broken on newest Eclector version

### ISSUE THREAD

**Issue by simendsjo** [coalton-lang/coalton#887]
Testing 45b0833d4b51a9cbb29f65ef891e5e2054df3bef, but I get an error both on Windows and Linux.

```
[package coalton-library/types].
; 
; caught COMMON-LISP:ERROR:
;   COMMON-LISP:READ error during COMMON-LISP:COMPILE-FILE:
;   
;     There is no applicable method for the generic function
;       #<COMMON-LISP:STANDARD-GENERIC-FUNCTION CONCRETE-SYNTAX-TREE:RECONSTRUCT (2)>
;     when called with arguments
;       (REPR COMMON-LISP:NIL
;             #<COALTON-IMPL/PARSER/READER::COALTON-ECLECTOR-CLIENT {10050DE4C3}>
;             :DEFAULT-SOURCE (401 . 405)).
;   See also:
;     The ANSI Standard, Section 7.6.6
;   
;     (in form starting at line: 19, column: 0, position: 380)
```

![image](https://user-images.githubusercontent.com/351519/231567776-730fb9bf-a5c4-4cee-91af-09aa8ea28fdc.png)

**Comment by eliaslfox** [comment]
Try `make cleanall` and then loading again. This might be a caching problem.

**Comment by simendsjo** [comment]
> Try make cleanall and then loading again. This might be a caching problem.

I suspected caching and deleted ~/.cache/common-lisp first. `make cleanall` doesn't remove the error either.

**Comment by colescott** [comment]
What quicklisp dist version are you on? It's working for me under quicklisp 2023-02-15 on sbcl 2.3.0.

**Comment by simendsjo** [comment]
> What quicklisp dist version are you on? It's working for me under quicklisp 2023-02-15 on sbcl 2.3.0.

2023-02-15 and sbcl 2.3.2 on Linux and I think sbcl 2.3.0 on Windows.

**Comment by colescott** [comment]
Do you have Eclector or concrete-syntax-tree checked out locally? My other thought is that one of the other dists is providing a different version of one of those packages.

**Comment by simendsjo** [comment]
> Do you have Eclector or concrete-syntax-tree checked out locally? My other thought is that one of the other dists is providing a different version of one of those packages.

Yes, that was the problem, thanks! By removing ultralisp, coalton compiles! I guess it's this project which causes problems: https://ultralisp.org/projects/robert-strandh/eclector.

I find quicklisp quite frustrating :/ Pretty large contrast to most other package managers which strives to be deterministic and keep versions around to not break code. With quicklisp it seems like I get a curated snapshot where each package builds in isolation and no way to pick different versions. And apparently cross-dist "polution". Using Guix as my OS, I'm contemplating on writing a Guix definition for things I use..

**Comment by colescott** [comment]
It seems like we might be broken on the newest version of Eclector. I can take a look into what has changed on their side since the last quicklisp dist release.

**Comment by colescott** [comment]
This appears to be caused by a breaking change to the cst api here: https://github.com/s-expressionists/Concrete-Syntax-Tree/pull/36
