### ISSUE TITLE
Move away from macros in the standard library

### ISSUE THREAD

**Issue by colescott** [coalton-lang/coalton#903]
There are a few places where we use macros to generate coalton code in the standard library such as https://github.com/coalton-lang/coalton/blob/main/library/math/num.lisp#L57.

I think we should move away from macro-generated code in the standard library. I find the macros to be hard to quickly understand, especially when you are trying to reference how a specific instance or value is defined. While the macros are able to decrease code size, I think this is not something we should optimize for over readability. Additionally, the documentation generator is planned to link values/types/instances' line numbers which are a bit iffy/unhelpful when multiple instances/types/values are defined in the same macro.

**Comment by stylewarning** [comment]
The counter-argument is that macros aren't actually optimizing for code size, as you suggest, but rather readability. At a glance one can see the treatment of a handful of types are treated identically, whereas if the code is blown up to 10x the size, not only would it be non-obvious, it would also require that multiplier of edits any time an incremental change to the treatment of any of the types is involved.

I'm sympathetic to not having "useless" macros that only serve a de-duplicative purpose, as is witnessed in a lot of supposedly clever Lisp code. I don't think it's necessarily out-of-line here, though. 

We've regularly been trading the expressiveness and concision of macros for implementation verbosity/complexity (but also incrementally improved compile-time DX), and I think it's worthwhile to ask ourselves—outside of this specific issue—how we might approach making macros more pleasant within Coalton proper and within Coalton's standard library. I think it's also worthwhile to ask ourselves why Lisp programmers haven't (typically) suffered from using macros for 40+ years now, but even small usages in Coalton cause an allergic reaction.

**Comment by stylewarning** [comment]
(Just as a concrete example suggestion, so I'm not speaking in vague generalities: What if the Coalton standard library code were written in a macro, but the macro were expanded within the treatment of a COALTON-TOPLEVEL, and as a default principle forbidding expansion of toplevel Lisp macros as toplevel COALTON-TOPLEVEL forms? That is:

```lisp
(defmacro def-foo ()
  ...)

(coalton-toplevel
  (def-foo))
```

and *not*:

```lisp
(defmacro def-foo ()
  `(coalton-toplevel ...))

(def-foo)
```

If we control macroexpansion, then we have total context to provide, and we benefit users' macros—which any self-respecting Lisp programmer will write—as well.)

**Comment by gefjon** [comment]
> The counter-argument is that macros aren't actually optimizing for code size, as you suggest, but rather readability. At a glance one can see the treatment of a handful of types are treated identically, whereas if the code is blown up to 10x the size, not only would it be non-obvious, it would also require that multiplier of edits any time an incremental change to the treatment of any of the types is involved.

I believe the macro-ful versions of repeated instance definitions e.g. on integer types is more readable, but I'm much more interested in the last thing @stylewarning mentions here. The macro-ful versions are much easier to maintain and offer fewer opportunities for typos, bugs and other accidental differences between instances that should be identical. It's very easy to miss one instance when changing a handful of characters in each, or paste a line between two instances and forget to replace `I32` with `I64` or `U32`. The macros eliminate that whole class of bugs and ensure that two instances which are supposed to be the same actually are.

**Comment by eliaslfox** [comment]
I think most of the current macro usage in the stdlib is totally reasonable. If anyone wants to re-write code to use fewer macros, it can be considered on a case by case basis.
