### ISSUE TITLE
Flattenable typeclass, or equivalent?

### ISSUE THREAD

**Issue by macrologist** [coalton-lang/coalton#911]
```
(define-class (Flattenable :container) 
  (flatten (:container (:container :t) -> :container :t)))

```

Possible instances: `List`, `Iterator`, `Optional` at least.

**Comment by eliaslfox** [comment]
flatten is just `(flip >>= id)`.

`(coalton (>>= (Some (Some 1)) id))` => `(Some 1)`

`(coalton (>>= (make-list (make-list 1 2 3) (make-list 4 5 6)) id))` => `(make-list 1 2 3 4 5 6)`
