### ISSUE TITLE
Org-babel errors with Coalton code block

### ISSUE THREAD

**Issue by Izaakwltn** [coalton-lang/coalton#980]
I tried experimenting with org-mode code blocks in Coalton and ran into a consistent error. This may be MacOS specific.

For Instance:
```
#+begin_src lisp
  (in-package #:coalton-user)
#+end_src
```
and 
```
#+begin_src lisp
  (in-package #:cl-user)
  (defpackage #:please-work
    (:use #:coalton
             #:coalton-prelude))                    ;; works until here

  (in-package #:please-work)
#+end_src
```
Both give the error: `The operator LET is only valid in a Coalton expression.`

For now, here's a rough workaround with a CL wrapper that *works*: 
```
#+begin_src lisp
  (ql:quickload :coalton)
  (defpackage #:lisp-coalton-wrap
    (:use #:cl))

  (in-package #:lisp-coalton-wrap)

  (defun test-sqrt (x)
    (eval `(coalton:coalton (coalton-library/math:sqrt ,x))))

  (test-sqrt 2)

#+end_src

#+RESULTS:
: 1.4142135623730951
```

**Comment by eliaslfox** [comment]
I think someone on the Discord ran into this before. Org babel appears to just be broken in packages that don't `:use` cl.
