### ISSUE TITLE
Error: A token consisting solely of multiple dots is illegal"

### ISSUE THREAD

**Issue by digikar99** [coalton-lang/coalton#983]
With the latest version of

- coalton
- s-expressionists/Eclector
- s-expressionists/Concrete-Syntax-Tree

And SBCL 2.3.7 (although `(lisp-implementation-version)` says "2.3.7-WIP")

I run into multiple errors similar to the following:

```
; file: /home/user/quicklisp/local-projects/coalton/library/math/conversions.lisp
; in: DEFINE-INTEGER-CONVERSIONS U8
;     (COALTON-LIBRARY/MATH/CONVERSIONS::DEFINE-INTEGER-CONVERSIONS COALTON:U8)
;
; caught COMMON-LISP:ERROR:
;   (during macroexpansion of (COALTON-TOPLEVEL
;     (DEFINE-INSTANCE #
;       ...)
;     ...))
;   A token consisting solely of multiple dots is illegal.
```

The error repeats for all of the other `(define-integer-conversions ...)` forms.

Are there particular dependency versions that do not cause this problem?

**Comment by eliaslfox** [comment]
I'm on the latest for all 3, and 2.3.7 and I'm not able to reproduce the issue. `-WIP` suffixes usually mean that you have a version of SBCL that was built from the master branch.

I would try in this order:
* make sure that the coalton checkout is clean
* use a non `-WIP` SBCL version
* remove cst and eclector clones and instead use the quicklisp versions

**Comment by digikar99** [comment]
Ah, okay, found the issues:

SBCL adds a "-WIP" suffix if there is any uncommitted change in the files during its compilation.

I ran into the same issue with the quicklisp versions of cst and eclector; and also SBCL 2.3.8. On some investigation of my `.sbclrc`, the error stemmed from `(setf *print-length* 10)` in my `.sbclrc`. Commenting it out or setting `*print-length*` to `NIL` before compiling `coalton` allows coalton to compile successfully.

Thanks for confirming!
